on:
  push:
    branches:
      - main
jobs:
  build-the-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Saying hello
        run: echo "Hello, universe!"

      - name: Checkout to branch
        uses: actions/checkout@v4

      - name: Build image
        run: docker build -f docker/Dockerfile -t todo-app .

  push-to-registry:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: bomsiwor
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                  push: true
                  tags: bomsiwor/be-todo-soulparking
      
  
  deploy-on-server:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET_KEY }}
          script: |
            echo "Hello, universe"
